### ISSUE TITLE
关于比较poolnet的问题

### ISSUE THREAD

**Issue by chiukin** [JosephChenHub/GCPANet#1]
请问下，你所比较的poolnet是原作者提供的显著图，还你通过代码重新生成的？我测了一下，我用原作者github提供的 PoolNet-ResNet50 w/ edge model (best performance) run-1 这个文件里的显著图， 和你提供poolnet对应的显著图得到的F值有所不同，所以问下你是怎么对比的

**Comment by StormArcher** [comment]
你好，请问你们都是能上外网下载的作者的模型吗，能否百度云提供一下文件

**Comment by JosephChenHub** [comment]
> 请问下，你所比较的poolnet是原作者提供的显著图，还你通过代码重新生成的？我测了一下，我用原作者github提供的 PoolNet-ResNet50 w/ edge model (best performance) run-1 这个文件里的显著图， 和你提供poolnet对应的显著图得到的F值有所不同，所以问下你是怎么对比的

The saliency maps are provided by the official code of PoolNet, which can be accessible from [google drive](https://drive.google.com/drive/folders/1JiIKySc3-IwfoUhNW7qNul9T3pfkqnYu) or its original repo. Besides, since additional data used in training of the PoolNet-ResNet50 w/edge model, for fair comparison, we compare the PoolNet-ResNet50 wo/edge.

**Comment by JosephChenHub** [comment]
> 你好，请问你们都是能上外网下载的作者的模型吗，能否百度云提供一下文件

Sorry for that , the model may be available in Baidu pan latter.
